### ISSUE TITLE
testnet 3 offline

### ISSUE THREAD

**Issue by nelseen** [ElixirProtocol/testnet-3-issue-tracker#2]
i will assume the network is current offline considering the logs below or is there issue here that im missing. thanks 

2024-08-29 23:36:14 [strategy_executor] [info] Starting validator timestamp=2024-08-30T03:36:14.281334Z version=3.1.0
2024-08-29 23:36:14 [strategy_executor] [info] Initializing health check service api timestamp=2024-08-30T03:36:14.341482Z
2024-08-29 23:36:14 [strategy_executor] [info] starting proposal processor timestamp=2024-08-30T03:36:14.358211Z
2024-08-29 23:36:14 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:14.389099Z
2024-08-29 23:36:14 INFO:     Started server process [27]
2024-08-29 23:36:14 INFO:     Waiting for application startup.
2024-08-29 23:36:14 INFO:     Application startup complete.
2024-08-29 23:36:14 INFO:     Uvicorn running on http://0.0.0.0:17690 (Press CTRL+C to quit)
2024-08-29 23:36:14 [strategy_executor] [info] Creating Elixir API service timestamp=2024-08-30T03:36:14.435258Z url=https://api.testnet-3.elixirdev.xyz
2024-08-29 23:36:14 [strategy_executor] [info] >>>> sending authorization request timestamp=2024-08-30T03:36:14.435663Z
2024-08-29 23:36:14 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:14.440301Z
2024-08-29 23:36:19 [strategy_executor] [error] error sending authorization request: Invalid response code 400 timestamp=2024-08-30T03:36:19.661066Z
2024-08-29 23:36:19 [strategy_executor] [error] Traceback (most recent call last):
2024-08-29 23:36:19   File "/app/services/strategy_executor/strategy_executor/executor.py", line 76, in authorize
2024-08-29 23:36:19     response = self.get_api().authorize(authorization_request)
2024-08-29 23:36:19   File "/app/services/strategy_executor/strategy_executor/api.py", line 46, in authorize
2024-08-29 23:36:19     raise UnauthorizedException(f"Invalid response code {response.status_code}")
2024-08-29 23:36:19 shared.exceptions.UnauthorizedException: Invalid response code 400
2024-08-29 23:36:19  timestamp=2024-08-30T03:36:19.662575Z
2024-08-29 23:36:24 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:24.400729Z
2024-08-29 23:36:24 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:24.452504Z
2024-08-29 23:36:34 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:34.413397Z
2024-08-29 23:36:34 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:34.463685Z
2024-08-29 23:36:44 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:44.425536Z
2024-08-29 23:36:44 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:44.476109Z
2024-08-29 23:36:54 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:54.437750Z
2024-08-29 23:36:54 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:36:54.488108Z
2024-08-29 23:37:04 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:04.439875Z
2024-08-29 23:37:04 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:04.501829Z
2024-08-29 23:37:14 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:14.451381Z
2024-08-29 23:37:14 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:14.514582Z
2024-08-29 23:37:19 [strategy_executor] [info] >>>> sending authorization request timestamp=2024-08-30T03:37:19.690433Z
2024-08-29 23:37:24 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:24.462405Z
2024-08-29 23:37:24 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:24.527412Z
2024-08-29 23:37:25 [strategy_executor] [error] error sending authorization request: Invalid response code 400 timestamp=2024-08-30T03:37:25.128197Z
2024-08-29 23:37:25 [strategy_executor] [error] Traceback (most recent call last):
2024-08-29 23:37:25   File "/app/services/strategy_executor/strategy_executor/executor.py", line 76, in authorize
2024-08-29 23:37:25     response = self.get_api().authorize(authorization_request)
2024-08-29 23:37:25   File "/app/services/strategy_executor/strategy_executor/api.py", line 46, in authorize
2024-08-29 23:37:25     raise UnauthorizedException(f"Invalid response code {response.status_code}")
2024-08-29 23:37:25 shared.exceptions.UnauthorizedException: Invalid response code 400
2024-08-29 23:37:25  timestamp=2024-08-30T03:37:25.128541Z
2024-08-29 23:37:34 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:34.473523Z
2024-08-29 23:37:34 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:34.539777Z
2024-08-29 23:37:44 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:44.485747Z
2024-08-29 23:37:44 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:44.551844Z
2024-08-29 23:37:54 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:54.487377Z
2024-08-29 23:37:54 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:37:54.563425Z
2024-08-29 23:38:04 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:04.496291Z
2024-08-29 23:38:04 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:04.574022Z
2024-08-29 23:38:14 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:14.507501Z
2024-08-29 23:38:14 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:14.592537Z
2024-08-29 23:38:24 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:24.520470Z
2024-08-29 23:38:24 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:24.604270Z
2024-08-29 23:38:25 [strategy_executor] [info] >>>> sending authorization request timestamp=2024-08-30T03:38:25.200186Z
2024-08-29 23:38:30 [strategy_executor] [error] error sending authorization request: Invalid response code 400 timestamp=2024-08-30T03:38:30.247773Z
2024-08-29 23:38:30 [strategy_executor] [error] Traceback (most recent call last):
2024-08-29 23:38:30   File "/app/services/strategy_executor/strategy_executor/executor.py", line 76, in authorize
2024-08-29 23:38:30     response = self.get_api().authorize(authorization_request)
2024-08-29 23:38:30   File "/app/services/strategy_executor/strategy_executor/api.py", line 46, in authorize
2024-08-29 23:38:30     raise UnauthorizedException(f"Invalid response code {response.status_code}")
2024-08-29 23:38:30 shared.exceptions.UnauthorizedException: Invalid response code 400
2024-08-29 23:38:30  timestamp=2024-08-30T03:38:30.248100Z
2024-08-29 23:38:34 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:34.535147Z
2024-08-29 23:38:34 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:34.612306Z
2024-08-29 23:38:44 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:44.546139Z
2024-08-29 23:38:44 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:44.624693Z
2024-08-29 23:38:54 [strategy_executor] [info] consumer is offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:54.557909Z
2024-08-29 23:38:54 [strategy_executor] [info] proposal producer offline, reconnecting in 10 seconds timestamp=2024-08-30T03:38:54.636909Z

**Comment by wim-web** [comment]
logs says "error sending authorization request: Invalid response code 400 timestamp=2024-08-30T03:36:19.661066Z"
so i guess something wrong env file(especially ip_address or beneficiary)
It would be better if you add what command you used to launch it

**Comment by ajelixir** [comment]
Please send us the values you are using the STRATEGY_EXECUTOR_IP_ADDRESS and STRATEGY_EXECUTOR_DISPLAY_NAME in your env file.  We are also working on including more error details in your logs.  This will be part of our next release.

**Comment by nelseen** [comment]
sure 
STRATEGY_EXECUTOR_IP_ADDRESS=73.16.76.166
STRATEGY_EXECUTOR_DISPLAY_NAME=nelseen 

and as for the wallet address, i understand that can be any wallet address as well as the private key to test 

command used: docker run --env-file /Users/nelson/Downloads/validator.env --platform linux/amd64 -p 17690:17690 elixirprotocol/validator:v3

**Comment by scripnichenko** [comment]
same for me today for a new node installation.

STRATEGY_EXECUTOR_IP_ADDRESS=158.220.99.103
STRATEGY_EXECUTOR_DISPLAY_NAME=🐹HamsterClub🐹
STRATEGY_EXECUTOR_BENEFICIARY has the metamask wallet for rewards/points
SIGNER_PRIVATE_KEY  is a private key from a newly/cristal-clear metamask wallet. Not the same as STRATEGY_EXECUTOR_BENEFICIARY.

@ajelixir  kindly check.

**Comment by scripnichenko** [comment]
Get it working after updating 
STRATEGY_EXECUTOR_DISPLAY_NAME: HamsterClub

It can be checked via API call:

POST https://api.testnet-3.elixirdev.xyz/auth/validator/authorize
Content-Type: application/json


``` json

{
  "detail": {
    "ip_address": "158.220.99.103",  
    "display_name": "HamsterClub",
    "beneficiary": "YOUR_WALLET",
    "app_version": "testnet-3" 
  },
  "proof": {
    "hash": "YOUR_HASH",
    "signature": "YOUR_SIGNATURE"
    }
}
```

**Comment by nelseen** [comment]
ok, I figured out the problem from my end. 
So my display name has been taken already, which is why it returned the offline error message. thanks, guys

**Comment by scripnichenko** [comment]
@nelseen  i had similar issue, i have emoji in a naming :) 
glad it works.

**Comment by nelseen** [comment]
@scripnichenko glad it worked for you as well.

**Comment by walirt** [comment]
> Get it working after updating STRATEGY_EXECUTOR_DISPLAY_NAME: HamsterClub
> 
> It can be checked via API call:
> 
> POST https://api.testnet-3.elixirdev.xyz/auth/validator/authorize Content-Type: application/json
> 
> ```json
> {
>   "detail": {
>     "ip_address": "158.220.99.103",  
>     "display_name": "HamsterClub",
>     "beneficiary": "YOUR_WALLET",
>     "app_version": "testnet-3" 
>   },
>   "proof": {
>     "hash": "YOUR_HASH",
>     "signature": "YOUR_SIGNATURE"
>     }
> }
> ```

hi, can I ask how to get the value of proof? I also have the same error
